<a href="https://colab.research.google.com/github/Manash-Christ/DAA-Trimester2/blob/main/DAA_CIA1_2348528.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [181]:
import time
from tqdm import tqdm
import numpy as np
import pandas as pd

In [182]:
# generate randomg lists of numbers
rng = np.random.default_rng()
def randgen(shuffle:bool=True,**kwargs):
  if shuffle:
    return rng.integers(low=0,high=100,size=rng.integers(50))
  else:
    return rng.integers(low=0,high=100,size=kwargs['size'])
randgen(False,size=9)

array([37, 64, 30, 83,  3, 24, 20,  9, 15])

In [205]:
# time
bubb  = pd.DataFrame(columns=['inputsize', 'avgtime'])
inse  = pd.DataFrame(columns=['inputsize', 'avgtime'],)
quic = pd.DataFrame(columns=['inputsize', 'avgtime'],)


In [211]:
# Bubble sort
def bubble(array):
  start = time.time()
  for p in tqdm(range(len(array))):
    print(f"iteration {p} --> array {array}")
    for q in tqdm(range(len(array)-p-1)):
      if array[q]>array[q+1]:
        array[q],array[q+1] = array[q+1],array[q]
        print(f"sorting iteration {q+1}",array)
  duration = time.time() - start
  bubb.loc[]({'inputsize':len(array),'avgtime':duration},ignore_index=True)
  return array


bubble([5,4,3,4,3,434,33,2,10])

  0%|          | 0/9 [00:00<?, ?it/s]

iteration 0 --> array [5, 4, 3, 4, 3, 434, 33, 2, 10]



100%|██████████| 8/8 [00:00<00:00, 21945.34it/s]


sorting iteration 1 [4, 5, 3, 4, 3, 434, 33, 2, 10]
sorting iteration 2 [4, 3, 5, 4, 3, 434, 33, 2, 10]
sorting iteration 3 [4, 3, 4, 5, 3, 434, 33, 2, 10]
sorting iteration 4 [4, 3, 4, 3, 5, 434, 33, 2, 10]
sorting iteration 6 [4, 3, 4, 3, 5, 33, 434, 2, 10]
sorting iteration 7 [4, 3, 4, 3, 5, 33, 2, 434, 10]
sorting iteration 8 [4, 3, 4, 3, 5, 33, 2, 10, 434]
iteration 1 --> array [4, 3, 4, 3, 5, 33, 2, 10, 434]



100%|██████████| 7/7 [00:00<00:00, 24987.34it/s]


sorting iteration 1 [3, 4, 4, 3, 5, 33, 2, 10, 434]
sorting iteration 3 [3, 4, 3, 4, 5, 33, 2, 10, 434]
sorting iteration 6 [3, 4, 3, 4, 5, 2, 33, 10, 434]
sorting iteration 7 [3, 4, 3, 4, 5, 2, 10, 33, 434]
iteration 2 --> array [3, 4, 3, 4, 5, 2, 10, 33, 434]



100%|██████████| 6/6 [00:00<00:00, 28565.07it/s]


sorting iteration 2 [3, 3, 4, 4, 5, 2, 10, 33, 434]
sorting iteration 5 [3, 3, 4, 4, 2, 5, 10, 33, 434]
iteration 3 --> array [3, 3, 4, 4, 2, 5, 10, 33, 434]



100%|██████████| 5/5 [00:00<00:00, 8939.27it/s]


sorting iteration 4 [3, 3, 4, 2, 4, 5, 10, 33, 434]
iteration 4 --> array [3, 3, 4, 2, 4, 5, 10, 33, 434]



100%|██████████| 4/4 [00:00<00:00, 25497.29it/s]


sorting iteration 3 [3, 3, 2, 4, 4, 5, 10, 33, 434]
iteration 5 --> array [3, 3, 2, 4, 4, 5, 10, 33, 434]



100%|██████████| 3/3 [00:00<00:00, 7401.71it/s]


sorting iteration 2 [3, 2, 3, 4, 4, 5, 10, 33, 434]
iteration 6 --> array [3, 2, 3, 4, 4, 5, 10, 33, 434]



100%|██████████| 2/2 [00:00<00:00, 12614.45it/s]


sorting iteration 1 [2, 3, 3, 4, 4, 5, 10, 33, 434]
iteration 7 --> array [2, 3, 3, 4, 4, 5, 10, 33, 434]



100%|██████████| 1/1 [00:00<00:00, 10106.76it/s]


iteration 8 --> array [2, 3, 3, 4, 4, 5, 10, 33, 434]



0it [00:00, ?it/s]
100%|██████████| 9/9 [00:00<00:00, 105.11it/s]


UnboundLocalError: ignored

In [210]:
bubb

Empty DataFrame
Columns: [inputsize, avgtime]
Index: []

In [156]:
def part(array,low,high):
  pivot = array[high]
  i = low - 1
  for j in range(low,high):
    if array[j]<=pivot:
      i+=1
      array[i],array[j] = array[j],array[i]
  array[i+1], array[high] = array[high], array[i+1]
  return i+1

def quick(array,low,high):
  if low<high:
    p = part(array,low,high)
    quick(array,low,p-1)
    quick(array,p+1,high)
  return array

array = randgen()
quick(array,0,len(array)-1)

array([ 0,  5,  7, 16, 17, 18, 21, 29, 47, 49, 50, 52, 53, 54, 57, 65, 69,
       72, 73, 86, 99])

In [177]:
def insert(array):
  for i in range(1,len(array)):
    j = i
    while array[j-1]>array[j] and j > 0:
      array[j-1],array[j] = array[j],array[j-1]
      j-=1
  return array

array = randgen()
insert(array)


array([ 1,  2,  2,  3,  4, 11, 13, 13, 18, 20, 23, 24, 36, 45, 48, 51, 52,
       53, 59, 65, 72, 77, 78, 78, 84, 87, 88, 89, 89, 93])

In [121]:
def randgen():
  return rng.integers(low=0,high=100,size=rng.integers(50))


In [134]:
arr = randgen()

In [143]:
i=2
++i


2

In [147]:
i++

SyntaxError: ignored